data = input().split()
a, b = int(data[0]), int(data[1])
print(1 if a >= b else 0)
print(1 if a > b else 0)
print(1 if b >= a else 0)
print(1 if b > a else 0)
print(1 if a == b else 0)
print(1 if a != b else 0)